"""Added Post table, hopefully no need for image table

Revision ID: 388223ae3f6c
Revises: 
Create Date: 2019-01-20 01:57:34.611465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '388223ae3f6c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folder', sa.String(length=100), nullable=True),
    sa.Column('image_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_folder'), 'post', ['folder'], unique=True)
    op.create_index(op.f('ix_post_image_count'), 'post', ['image_count'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_image_count'), table_name='post')
    op.drop_index(op.f('ix_post_folder'), table_name='post')
    op.drop_table('post')
    # ### end Alembic commands ###
